name: Test VM Build
run-name: Testing VM Build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y virtualbox
      - run: packer init .
      - run: packer build rocky9.json.pkr.hcl
